### ISSUE TITLE
Failed to download video.

### ISSUE THREAD

**Issue by sayemsarkar123** [kyonenjs/udeguchi#9]
Please check your mail for details.

**Comment by kyonenjs** [comment]
Hello @sayemsarkar123,

I think the server is a little bit unstable at this moment. You can try another time.

Or you can use new command option "--no-hls", it'll use normal https server instead of streaming server.

Let's me know if you still see the error even with new command option.

**Comment by kyonenjs** [comment]
You can try use a VPN if you have. It works fine when i'm using VPN

![Capture(1)](https://user-images.githubusercontent.com/52479148/79182104-2a3b0200-7e38-11ea-9d40-b550c12e2b3f.png)

**Comment by sayemsarkar123** [comment]
@kyonenjs --no-hls is work fine. but yet streaming has problem i'm useing microsoft azure rdp.

**Comment by kyonenjs** [comment]
@sayemsarkar123 they're doing some stuffs with their streaming.

First thing i noticed is now you need to authenticate when make a request with hls (streaming) link. Not like before when you can just download that link without authenticate.

Second thing is structure of the response from hls link, some course i download without problem before but now i can't even start the download, which i already fixed in lastest commit.

Third thing is download stuck at some point, but if i stop and re-run the program or use VPN, it works fine.

So maybe it need a little bit of time for them to do things on their side with their streaming server. For right now i think if you can, please use "--no-hls" option or try use VPN like me.

**Comment by kyonenjs** [comment]
Hello @sayemsarkar123

![Capture(1)](https://user-images.githubusercontent.com/52479148/79425431-e25cdc00-7feb-11ea-802a-b5cb2adda404.png)

I finally met the same error as you. (No '--no-hls' option)

I already fixed it in lastest commit. Please update udeguchi and let me know if you still see the error.
